set -g prefix C-x
unbind C-b


bind r source-file ~/.tmux.conf \; display "Reloaded!"
# split window
unbind '"'
# vertical split (prefix -)
bind h splitw -v
unbind %
bind v splitw -h # horizontal split (prefix |)
#up
bind-key k select-pane -U
#down
bind-key j select-pane -D
#left
bind-key h select-pane -L
#right
bind-key l select-pane -R

bind-key C-l select-window -l

setw -g mode-keys vi

bind -r ^k resizep -U 10 # upward (prefix Ctrl+k)
bind -r ^j resizep -D 10 # downward (prefix Ctrl+j)
bind -r ^h resizep -L 10 # to the left (prefix Ctrl+h)
bind -r ^l resizep -R 10 # to the right (prefix Ctrl+l)

# swap pane
# swap with the previous pane (prefix Ctrl+u)
bind ^u swapp -U
# swap with the next pane (prefix Ctrl+d)
bind ^d swapp -D
