#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Microsoft-edge desktop='^2'
bspc rule -a Alacritty desktop='^1'
bspc rule -a netease-cloud-music  desktop'^0' 
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Xmodmap
xmodmap /home/waytrue/stow/Xmodmap &
# Cursor
xsetroot -cursor_name left_ptr &
# Pinyin
fcixt-autostart &
fcitx5 &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

bspc rule -a Alacritty state=tiled manage=on layer=normal private=on follow=on
bspc rule -a scrcpy state=pseudo_tiled manage=on layer=normal private=on follow=on
bspc rule -a QtScrcpy state=floating manage=on layer=normal 
bspc rule -a scrcpy state=pseudo_tiled manage=on layer=normal private=on follow=on
